title: nervouslyopen.com
description: Official support and app pages for SleepySheepie and Journly
author: vudam991
url: https://nervouslyopen.com

markdown: kramdown
kramdown:
  input: GFM

repository: vudam991/nervouslyopen.com
remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme

# Build settings
exclude:
  - .github/
  - _site/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - vendor/